# Generated by Django 2.2.4 on 2021-12-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0005_auto_20211225_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
